"""Build every case in a scratch directory, run the baseline and the P/R/O verifier, print the table.

Usage: python run_cases.py [--out results/results.md]
Exit code 1 if any observed verdict differs from the expected one.
"""
from __future__ import annotations

import argparse
import json
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

from baseline import b43
from cases import CASES, TODAY, Case
from pro.scanner import scan
from pro.verifier import reconcile


@dataclass
class Result:
    case: Case
    baseline: str
    baseline_waived: str | None
    pro: str
    pro_findings: list[str]
    baseline_drifts: list[str]


def run_case(case: Case) -> Result:
    root = case.root
    base = b43.check(root, today=TODAY)
    waived = None
    if case.blanket_waiver_path:
        (root / "baseline/waivers.json").write_text(json.dumps([{"path": case.blanket_waiver_path, "reason": "blanket exemption", "expires": "2026-12-31"}]), encoding="utf-8")
        waived = b43.check(root, today=TODAY).verdict
        (root / "baseline/waivers.json").write_text("[]\n", encoding="utf-8")
    O = scan(root, case.P, case.R, case.cap)
    rep = reconcile(root, case.P_prev, case.P, case.R, O, case.cap, today=TODAY)
    return Result(case, base.verdict, waived, rep.verdict,
                  [f"{f.invariant}: {f.subject} -- {f.detail}" for f in rep.findings], base.drifts)


def run_all(workdir: Path | None = None) -> list[Result]:
    results = []
    for factory in CASES:
        tmp = Path(tempfile.mkdtemp(prefix="gdv-", dir=workdir))
        results.append(run_case(factory(tmp)))
    return results


def table(results: list[Result]) -> str:
    rows = ["| Case | Mutation | Baseline B4.3 | Baseline + blanket exemption | P/R/O verdict | Expected (baseline / P/R/O) | Agrees |",
            "|---|---|---|---|---|---|---|"]
    for r in results:
        exp = r.case.expected
        ok = r.baseline == exp["baseline"] and r.pro == exp["pro"] and (r.baseline_waived == exp.get("baseline_waived"))
        rows.append(f"| {r.case.name} | {r.case.description} | {r.baseline} | {r.baseline_waived or '—'} | {r.pro} | {exp['baseline']} / {exp['pro']} | {'yes' if ok else 'NO'} |")
    return "\n".join(rows)


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="results/results.md")
    args = ap.parse_args()
    results = run_all()
    md = table(results)
    print(md)
    detail = []
    for r in results:
        detail.append(f"\n### {r.case.name}\n\n{r.case.description}\n\n- baseline drifts: {r.baseline_drifts or 'none'}\n- P/R/O findings:")
        detail.extend(f"  - {f}" for f in (r.pro_findings or ["none"]))
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("# Executable illustration: verdicts per case\n\nGenerated by run_cases.py; scanner capability map C_v1 = {md, toml, py}; fixture runners {py, toml}; today fixed at 2026-09-02.\n\n" + md + "\n" + "\n".join(detail) + "\n", encoding="utf-8")
    bad = [r for r in results if not (r.baseline == r.case.expected["baseline"] and r.pro == r.case.expected["pro"]
                                      and r.baseline_waived == r.case.expected.get("baseline_waived"))]
    print(f"\n{len(results) - len(bad)}/{len(results)} cases agree with the expected verdicts; written {out}")
    return 1 if bad else 0


if __name__ == "__main__":
    sys.exit(main())
